#端口设置
server:
  port: 8082

#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testalipay?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: chenyicai
    password: cyc1234


#日志级别（一般设置为INFO）
logging:
  level:
    cn:
      edu:
        guet:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.guet.bean


